### ISSUE TITLE
com.sun.star.document.UpdateDocMode.QUIET_UPDATE

### ISSUE THREAD

**Issue by ghost** [unoconv/unoconv#399]
having unoconv 0.7 on archlinux, I can no longer use it with libreoffice-fresh-5.3.3-2
but after downgrading to libreoffice-still-5.2.7-1 it worked again.

This is the error encountered:

> richard@sarchx64:/home/richard/src/trytond-patches$ unoconv -v
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1236, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/usr/lib/python3.6/site-packages/uno.py", line 431, in _uno_import
    raise uno_import_exc
  File "/usr/lib/python3.6/site-packages/uno.py", line 353, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)

Is this a bug in LO or is QUIET_UPDATE obsoleted?

**Comment by kochie** [comment]
Getting the same error on arch.

**Comment by rochelmeyer** [comment]
Seems to be specific for arch. On another machine with ubuntu16.04Server it works flawless

**Comment by lynxor** [comment]
same issue here

**Comment by produnis** [comment]
any hints, someone?

**Comment by scara** [comment]
Same as #258: it looks like the only workaround is downgrading or trying to run the Python runtime of your office suite (in case of version mismatching).

HTH,
Matteo

**Comment by risto3** [comment]
oups, accidently reported in #258 that libreoffice-still no longer works as a workaround since moving to 5.3.5-1, so the heat is on getting this working again.

Tried putting the following exception handler around the failing statement
```
    try:
        from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
    except ImportError:
        QUIET_UPDATE = 1
```
still seems to have issues accessing the subsystem:

```
richard@sarchx64:/tmp/makepkg/unoconv/src/unoconv-0.7$ python -c 'import uno, unohelper'   # works okay
richard@sarchx64:/tmp/makepkg/unoconv/src/unoconv-0.7$ python unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630]
Traceback (most recent call last):
  File "unoconv", line 1273, in <module>
    op = Options(sys.argv[1:])
  File "unoconv", line 629, in __init__
    self.version()
  File "unoconv", line 688, in version
    product = uno.getComponentContext().ServiceManager.createInstance("com.sun.star.configuration.ConfigurationProvider").createInstanceWithArguments("com.sun.star.configuration.ConfigurationAccess", UnoProps(nodepath="/org.openoffice.Setup/Product"))
AttributeError: 'NoneType' object has no attribute 'createInstanceWithArguments'
```

**Comment by risto3** [comment]
I believe there is a build/dist problem, as I downloaded the PKGBUILD file with patches for libreoffice-fresh and did a local build. The first try to build failed seemingly because I had `gcc-libs-multilib` installed which has `libgfortran.so.3` instead of `libgfortran.so.4`. After replacing with `gcc-libs` the build was successful and miraculously enough unoconv works then just fine.
I'll cross file this to archlinux.

**Comment by regebro** [comment]
Sound like it solved. Closing. If it isn't, reopen it,

**Comment by regebro** [comment]
The same problem happens on macOS. :-/

**Comment by esperienzia** [comment]
I'm working on Heroku using Ubuntu 16.04.

I just found the way to make unconv work (almost) using this selfmade buildback: https://github.com/esperienzia/heroku-buildpack-unoconv-1

Now when i run the unoconv command (even alone), I get:

```
Traceback (most recent call last):
  File "/app/.apt/usr/bin/unoconv", line 1236, in <module>
    from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 342, in _uno_import
    raise uno_import_exc
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
  File "/app/.apt/usr/lib/python3/dist-packages/uno.py", line 268, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)
```

Someone has news on this?
